name: Build & Release Android App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui-android

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      # On recrée le fichier keystore à partir du secret
      - name: Restore Keystore
        run: |
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.ANDROID_KEYSTORE_BASE64 }}")
          [IO.File]::WriteAllBytes("budget-app.keystore", $pfx_cert_byte)

      # Compilation + Signature en une seule commande
      - name: Publish Android APK
        run: |
          dotnet publish Budget.Mobile/Budget.Mobile.csproj -f net10.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=budget-app.keystore -p:AndroidSigningKeyAlias="${{ secrets.ANDROID_KEY_ALIAS }}" -p:AndroidSigningKeyPass="${{ secrets.ANDROID_KEY_PASSWORD }}" -p:AndroidSigningStorePass="${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" -o ./Output
      # On sauvegarde l'APK signé
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BudgetApp-Android
          path: ./Output/*.apk
          
      # (Bonus) On sauvegarde le AAB (pour le Play Store)
      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BudgetApp-Android-Store
          path: ./Output/*.aab